"""initial schema

Revision ID: 9cbdc47da906
Revises: 
Create Date: 2026-05-29 21:46:35.336848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbdc47da906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_lead_time_days', sa.Float(), nullable=False),
    sa.Column('default_safety_stock', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_lead_time_days', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_sku_company_code')
    )
    with op.batch_alter_table('sku', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_code'), ['code'], unique=False)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ordered_at', sa.Date(), nullable=False),
    sa.Column('expected_at', sa.Date(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('is_backorder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_sku_id'), ['sku_id'], unique=False)

    op.create_table('sale_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_event_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_event_sku_id'), ['sku_id'], unique=False)

    op.create_table('stock_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.Column('on_order', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_snapshot_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshot_sku_id'), ['sku_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_snapshot_sku_id'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshot_observed_at'))

    op.drop_table('stock_snapshot')
    with op.batch_alter_table('sale_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_event_sku_id'))
        batch_op.drop_index(batch_op.f('ix_sale_event_occurred_at'))

    op.drop_table('sale_event')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_sku_id'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('sku', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_code'))

    op.drop_table('sku')
    op.drop_table('supplier')
    op.drop_table('company')
    # ### end Alembic commands ###
